<?xml version="1.0" encoding="UTF-8"?>
<testsuite failures="7" tests="50" skipped="0" name="CompanyServiceRegression" assertions="245" time="10.20063" errors="8">
  <testcase name="test_companies_batch_read" assertions="8" time="0.242823">
  </testcase>
  <testcase name="test_companies_by_limit_1" assertions="0" time="0.21273">
    <failure type="ArgumentError" message="wrong number of arguments (1 for 0)">
wrong number of arguments (1 for 0) (ArgumentError)
regression.rb:298:in `min'
regression.rb:298:in `test_companies_by_limit_1'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `__send__'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `run_test'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:320:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnermediator.rb:48:in `run_suite'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:82:in `start_mediator'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:52:in `start'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:304:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:52:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit.rb:321
regression.rb:343    </failure>
  </testcase>
  <testcase name="test_companies_by_limit_10" assertions="0" time="0.279437">
    <failure type="ArgumentError" message="wrong number of arguments (1 for 0)">
wrong number of arguments (1 for 0) (ArgumentError)
regression.rb:298:in `min'
regression.rb:298:in `test_companies_by_limit_10'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `__send__'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `run_test'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:320:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnermediator.rb:48:in `run_suite'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:82:in `start_mediator'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:52:in `start'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:304:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:52:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit.rb:321
regression.rb:343    </failure>
  </testcase>
  <testcase name="test_companies_by_limit_15" assertions="0" time="0.211832">
    <failure type="ArgumentError" message="wrong number of arguments (1 for 0)">
wrong number of arguments (1 for 0) (ArgumentError)
regression.rb:298:in `min'
regression.rb:298:in `test_companies_by_limit_15'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `__send__'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `run_test'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:320:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnermediator.rb:48:in `run_suite'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:82:in `start_mediator'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:52:in `start'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:304:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:52:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit.rb:321
regression.rb:343    </failure>
  </testcase>
  <testcase name="test_companies_by_limit_20" assertions="0" time="0.27337">
    <failure type="ArgumentError" message="wrong number of arguments (1 for 0)">
wrong number of arguments (1 for 0) (ArgumentError)
regression.rb:298:in `min'
regression.rb:298:in `test_companies_by_limit_20'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `__send__'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `run_test'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:320:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnermediator.rb:48:in `run_suite'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:82:in `start_mediator'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:52:in `start'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:304:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:52:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit.rb:321
regression.rb:343    </failure>
  </testcase>
  <testcase name="test_companies_by_limit_25" assertions="0" time="0.231841">
    <failure type="ArgumentError" message="wrong number of arguments (1 for 0)">
wrong number of arguments (1 for 0) (ArgumentError)
regression.rb:298:in `min'
regression.rb:298:in `test_companies_by_limit_25'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `__send__'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `run_test'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:320:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnermediator.rb:48:in `run_suite'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:82:in `start_mediator'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:52:in `start'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:304:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:52:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit.rb:321
regression.rb:343    </failure>
  </testcase>
  <testcase name="test_companies_by_limit_30" assertions="0" time="0.238864">
    <failure type="ArgumentError" message="wrong number of arguments (1 for 0)">
wrong number of arguments (1 for 0) (ArgumentError)
regression.rb:298:in `min'
regression.rb:298:in `test_companies_by_limit_30'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `__send__'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `run_test'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:320:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnermediator.rb:48:in `run_suite'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:82:in `start_mediator'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:52:in `start'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:304:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:52:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit.rb:321
regression.rb:343    </failure>
  </testcase>
  <testcase name="test_companies_by_limit_35" assertions="0" time="0.242082">
    <failure type="ArgumentError" message="wrong number of arguments (1 for 0)">
wrong number of arguments (1 for 0) (ArgumentError)
regression.rb:298:in `min'
regression.rb:298:in `test_companies_by_limit_35'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `__send__'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `run_test'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:320:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnermediator.rb:48:in `run_suite'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:82:in `start_mediator'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:52:in `start'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:304:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:52:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit.rb:321
regression.rb:343    </failure>
  </testcase>
  <testcase name="test_companies_by_limit_5" assertions="0" time="0.211217">
    <failure type="ArgumentError" message="wrong number of arguments (1 for 0)">
wrong number of arguments (1 for 0) (ArgumentError)
regression.rb:298:in `min'
regression.rb:298:in `test_companies_by_limit_5'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `__send__'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `run_test'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:320:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnermediator.rb:48:in `run_suite'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:82:in `start_mediator'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:52:in `start'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:304:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:52:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit.rb:321
regression.rb:343    </failure>
  </testcase>
  <testcase name="test_companies_by_offset_100" assertions="3" time="0.215943">
    <failure type="Test::Unit::AssertionFailedError" message="The company code values are equal for 100....">
The company code values are equal for 100.
&lt;nil&gt; expected to be =~
&lt;nil&gt;. (Test::Unit::AssertionFailedError)
regression.rb:285:in `test_companies_by_offset_100'    </failure>
  </testcase>
  <testcase name="test_companies_by_offset_14" assertions="4" time="0.216392">
  </testcase>
  <testcase name="test_companies_by_offset_4" assertions="4" time="0.222853">
  </testcase>
  <testcase name="test_companies_by_offset_50" assertions="4" time="0.204007">
  </testcase>
  <testcase name="test_companies_by_offset_53" assertions="4" time="0.21021">
  </testcase>
  <testcase name="test_companies_by_offset_68" assertions="3" time="0.210406">
    <failure type="Test::Unit::AssertionFailedError" message="The company code values are equal for 68....">
The company code values are equal for 68.
&lt;nil&gt; expected to be =~
&lt;nil&gt;. (Test::Unit::AssertionFailedError)
regression.rb:285:in `test_companies_by_offset_68'    </failure>
  </testcase>
  <testcase name="test_companies_by_offset_72" assertions="3" time="0.211115">
    <failure type="Test::Unit::AssertionFailedError" message="The company code values are equal for 72....">
The company code values are equal for 72.
&lt;nil&gt; expected to be =~
&lt;nil&gt;. (Test::Unit::AssertionFailedError)
regression.rb:285:in `test_companies_by_offset_72'    </failure>
  </testcase>
  <testcase name="test_companies_by_offset_88" assertions="3" time="0.223328">
    <failure type="Test::Unit::AssertionFailedError" message="The company code values are equal for 88....">
The company code values are equal for 88.
&lt;nil&gt; expected to be =~
&lt;nil&gt;. (Test::Unit::AssertionFailedError)
regression.rb:285:in `test_companies_by_offset_88'    </failure>
  </testcase>
  <testcase name="test_companies_by_sort" assertions="88" time="0.224912">
  </testcase>
  <testcase name="test_company_by_id_11" assertions="4" time="0.179561">
  </testcase>
  <testcase name="test_company_by_id_14" assertions="4" time="0.191025">
  </testcase>
  <testcase name="test_company_by_id_15" assertions="4" time="0.181236">
  </testcase>
  <testcase name="test_company_by_id_16" assertions="4" time="0.185494">
  </testcase>
  <testcase name="test_company_by_id_18" assertions="4" time="0.189065">
  </testcase>
  <testcase name="test_company_by_id_2" assertions="4" time="0.196469">
  </testcase>
  <testcase name="test_company_by_id_20" assertions="4" time="0.203885">
  </testcase>
  <testcase name="test_company_by_id_21" assertions="4" time="0.186715">
  </testcase>
  <testcase name="test_company_by_id_22" assertions="4" time="0.180994">
  </testcase>
  <testcase name="test_company_by_id_23" assertions="4" time="0.178757">
  </testcase>
  <testcase name="test_company_by_id_24" assertions="4" time="0.18369">
  </testcase>
  <testcase name="test_company_by_id_25" assertions="4" time="0.186066">
  </testcase>
  <testcase name="test_company_by_id_26" assertions="4" time="0.19095">
  </testcase>
  <testcase name="test_company_by_id_27" assertions="4" time="0.196221">
  </testcase>
  <testcase name="test_company_by_id_28" assertions="3" time="0.224163">
    <failure type="Test::Unit::AssertionFailedError" message="The company code values are equal for 28....">
The company code values are equal for 28.
&lt;nil&gt; expected to be =~
&lt;nil&gt;. (Test::Unit::AssertionFailedError)
regression.rb:259:in `test_company_by_id_28'    </failure>
  </testcase>
  <testcase name="test_company_by_id_29" assertions="3" time="0.183623">
    <failure type="Test::Unit::AssertionFailedError" message="The company code values are equal for 29....">
The company code values are equal for 29.
&lt;nil&gt; expected to be =~
&lt;nil&gt;. (Test::Unit::AssertionFailedError)
regression.rb:259:in `test_company_by_id_29'    </failure>
  </testcase>
  <testcase name="test_company_by_id_3" assertions="4" time="0.18112">
  </testcase>
  <testcase name="test_company_by_id_30" assertions="4" time="0.195558">
  </testcase>
  <testcase name="test_company_by_id_31" assertions="4" time="0.185222">
  </testcase>
  <testcase name="test_company_by_id_32" assertions="4" time="0.191378">
  </testcase>
  <testcase name="test_company_by_id_33" assertions="4" time="0.192839">
  </testcase>
  <testcase name="test_company_by_id_34" assertions="3" time="0.179391">
    <failure type="Test::Unit::AssertionFailedError" message="The company code values are equal for 34....">
The company code values are equal for 34.
&lt;nil&gt; expected to be =~
&lt;nil&gt;. (Test::Unit::AssertionFailedError)
regression.rb:259:in `test_company_by_id_34'    </failure>
  </testcase>
  <testcase name="test_company_by_id_35" assertions="4" time="0.185906">
  </testcase>
  <testcase name="test_company_by_id_36" assertions="4" time="0.182747">
  </testcase>
  <testcase name="test_company_by_id_4" assertions="4" time="0.179006">
  </testcase>
  <testcase name="test_company_by_id_5" assertions="4" time="0.185546">
  </testcase>
  <testcase name="test_company_by_id_6" assertions="4" time="0.185126">
  </testcase>
  <testcase name="test_company_by_id_7" assertions="4" time="0.19591">
  </testcase>
  <testcase name="test_company_by_id_8" assertions="4" time="0.186259">
  </testcase>
  <testcase name="test_company_by_id_9" assertions="4" time="0.185381">
  </testcase>
  <testcase name="test_company_by_name" assertions="4" time="0.229175">
  </testcase>
  <testcase name="test_connection" assertions="0" time="0.063666">
  </testcase>
  <system-out>
  </system-out>
  <system-err>
  </system-err>
</testsuite>
