<?xml version="1.0" encoding="UTF-8"?>
<testsuite failures="5" tests="50" skipped="0" name="CompanyServiceRegression" assertions="247" time="10.618299" errors="8">
  <testcase name="test_companies_batch_read" assertions="8" time="0.607067">
  </testcase>
  <testcase name="test_companies_by_limit_1" assertions="0" time="0.19585">
    <failure type="ArgumentError" message="wrong number of arguments (1 for 0)">
wrong number of arguments (1 for 0) (ArgumentError)
regression.rb:298:in `min'
regression.rb:298:in `test_companies_by_limit_1'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `__send__'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `run_test'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:320:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnermediator.rb:48:in `run_suite'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:82:in `start_mediator'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:52:in `start'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:304:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:52:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit.rb:321
regression.rb:343    </failure>
  </testcase>
  <testcase name="test_companies_by_limit_10" assertions="0" time="0.273103">
    <failure type="ArgumentError" message="wrong number of arguments (1 for 0)">
wrong number of arguments (1 for 0) (ArgumentError)
regression.rb:298:in `min'
regression.rb:298:in `test_companies_by_limit_10'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `__send__'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `run_test'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:320:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnermediator.rb:48:in `run_suite'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:82:in `start_mediator'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:52:in `start'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:304:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:52:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit.rb:321
regression.rb:343    </failure>
  </testcase>
  <testcase name="test_companies_by_limit_15" assertions="0" time="0.26065">
    <failure type="ArgumentError" message="wrong number of arguments (1 for 0)">
wrong number of arguments (1 for 0) (ArgumentError)
regression.rb:298:in `min'
regression.rb:298:in `test_companies_by_limit_15'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `__send__'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `run_test'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:320:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnermediator.rb:48:in `run_suite'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:82:in `start_mediator'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:52:in `start'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:304:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:52:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit.rb:321
regression.rb:343    </failure>
  </testcase>
  <testcase name="test_companies_by_limit_20" assertions="0" time="0.290853">
    <failure type="ArgumentError" message="wrong number of arguments (1 for 0)">
wrong number of arguments (1 for 0) (ArgumentError)
regression.rb:298:in `min'
regression.rb:298:in `test_companies_by_limit_20'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `__send__'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `run_test'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:320:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnermediator.rb:48:in `run_suite'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:82:in `start_mediator'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:52:in `start'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:304:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:52:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit.rb:321
regression.rb:343    </failure>
  </testcase>
  <testcase name="test_companies_by_limit_25" assertions="0" time="0.291897">
    <failure type="ArgumentError" message="wrong number of arguments (1 for 0)">
wrong number of arguments (1 for 0) (ArgumentError)
regression.rb:298:in `min'
regression.rb:298:in `test_companies_by_limit_25'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `__send__'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `run_test'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:320:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnermediator.rb:48:in `run_suite'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:82:in `start_mediator'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:52:in `start'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:304:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:52:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit.rb:321
regression.rb:343    </failure>
  </testcase>
  <testcase name="test_companies_by_limit_30" assertions="0" time="0.229065">
    <failure type="ArgumentError" message="wrong number of arguments (1 for 0)">
wrong number of arguments (1 for 0) (ArgumentError)
regression.rb:298:in `min'
regression.rb:298:in `test_companies_by_limit_30'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `__send__'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `run_test'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:320:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnermediator.rb:48:in `run_suite'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:82:in `start_mediator'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:52:in `start'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:304:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:52:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit.rb:321
regression.rb:343    </failure>
  </testcase>
  <testcase name="test_companies_by_limit_35" assertions="0" time="0.235095">
    <failure type="ArgumentError" message="wrong number of arguments (1 for 0)">
wrong number of arguments (1 for 0) (ArgumentError)
regression.rb:298:in `min'
regression.rb:298:in `test_companies_by_limit_35'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `__send__'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `run_test'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:320:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnermediator.rb:48:in `run_suite'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:82:in `start_mediator'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:52:in `start'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:304:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:52:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit.rb:321
regression.rb:343    </failure>
  </testcase>
  <testcase name="test_companies_by_limit_5" assertions="0" time="0.21491">
    <failure type="ArgumentError" message="wrong number of arguments (1 for 0)">
wrong number of arguments (1 for 0) (ArgumentError)
regression.rb:298:in `min'
regression.rb:298:in `test_companies_by_limit_5'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `__send__'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:452:in `run_test'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testcase.rb:320:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:38:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `each'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/testsuite.rb:37:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnermediator.rb:48:in `run_suite'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:82:in `start_mediator'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/console/testrunner.rb:52:in `start'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:304:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit/autorunner.rb:52:in `run'
/opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.9/lib/test/unit.rb:321
regression.rb:343    </failure>
  </testcase>
  <testcase name="test_companies_by_offset_100" assertions="3" time="0.2156">
    <failure type="Test::Unit::AssertionFailedError" message="The company code values are equal for 100....">
The company code values are equal for 100.
&lt;nil&gt; expected to be =~
&lt;nil&gt;. (Test::Unit::AssertionFailedError)
regression.rb:285:in `test_companies_by_offset_100'    </failure>
  </testcase>
  <testcase name="test_companies_by_offset_14" assertions="4" time="0.21677">
  </testcase>
  <testcase name="test_companies_by_offset_4" assertions="4" time="0.211207">
  </testcase>
  <testcase name="test_companies_by_offset_50" assertions="4" time="0.206573">
  </testcase>
  <testcase name="test_companies_by_offset_53" assertions="4" time="0.204106">
  </testcase>
  <testcase name="test_companies_by_offset_68" assertions="4" time="0.21486">
  </testcase>
  <testcase name="test_companies_by_offset_72" assertions="4" time="0.216364">
  </testcase>
  <testcase name="test_companies_by_offset_88" assertions="3" time="0.224385">
    <failure type="Test::Unit::AssertionFailedError" message="The company code values are equal for 88....">
The company code values are equal for 88.
&lt;nil&gt; expected to be =~
&lt;nil&gt;. (Test::Unit::AssertionFailedError)
regression.rb:285:in `test_companies_by_offset_88'    </failure>
  </testcase>
  <testcase name="test_companies_by_sort" assertions="88" time="0.222817">
  </testcase>
  <testcase name="test_company_by_id_11" assertions="4" time="0.176141">
  </testcase>
  <testcase name="test_company_by_id_14" assertions="4" time="0.204679">
  </testcase>
  <testcase name="test_company_by_id_15" assertions="4" time="0.211098">
  </testcase>
  <testcase name="test_company_by_id_16" assertions="4" time="0.18857">
  </testcase>
  <testcase name="test_company_by_id_18" assertions="4" time="0.185152">
  </testcase>
  <testcase name="test_company_by_id_2" assertions="4" time="0.181635">
  </testcase>
  <testcase name="test_company_by_id_20" assertions="4" time="0.191789">
  </testcase>
  <testcase name="test_company_by_id_21" assertions="4" time="0.186032">
  </testcase>
  <testcase name="test_company_by_id_22" assertions="4" time="0.180119">
  </testcase>
  <testcase name="test_company_by_id_23" assertions="4" time="0.184091">
  </testcase>
  <testcase name="test_company_by_id_24" assertions="4" time="0.189876">
  </testcase>
  <testcase name="test_company_by_id_25" assertions="4" time="0.201073">
  </testcase>
  <testcase name="test_company_by_id_26" assertions="4" time="0.193957">
  </testcase>
  <testcase name="test_company_by_id_27" assertions="4" time="0.190304">
  </testcase>
  <testcase name="test_company_by_id_28" assertions="3" time="0.181312">
    <failure type="Test::Unit::AssertionFailedError" message="The company code values are equal for 28....">
The company code values are equal for 28.
&lt;nil&gt; expected to be =~
&lt;nil&gt;. (Test::Unit::AssertionFailedError)
regression.rb:259:in `test_company_by_id_28'    </failure>
  </testcase>
  <testcase name="test_company_by_id_29" assertions="3" time="0.184479">
    <failure type="Test::Unit::AssertionFailedError" message="The company code values are equal for 29....">
The company code values are equal for 29.
&lt;nil&gt; expected to be =~
&lt;nil&gt;. (Test::Unit::AssertionFailedError)
regression.rb:259:in `test_company_by_id_29'    </failure>
  </testcase>
  <testcase name="test_company_by_id_3" assertions="4" time="0.179042">
  </testcase>
  <testcase name="test_company_by_id_30" assertions="4" time="0.180395">
  </testcase>
  <testcase name="test_company_by_id_31" assertions="4" time="0.186948">
  </testcase>
  <testcase name="test_company_by_id_32" assertions="4" time="0.18107">
  </testcase>
  <testcase name="test_company_by_id_33" assertions="4" time="0.19847">
  </testcase>
  <testcase name="test_company_by_id_34" assertions="3" time="0.187729">
    <failure type="Test::Unit::AssertionFailedError" message="The company code values are equal for 34....">
The company code values are equal for 34.
&lt;nil&gt; expected to be =~
&lt;nil&gt;. (Test::Unit::AssertionFailedError)
regression.rb:259:in `test_company_by_id_34'    </failure>
  </testcase>
  <testcase name="test_company_by_id_35" assertions="4" time="0.181751">
  </testcase>
  <testcase name="test_company_by_id_36" assertions="4" time="0.185333">
  </testcase>
  <testcase name="test_company_by_id_4" assertions="4" time="0.189353">
  </testcase>
  <testcase name="test_company_by_id_5" assertions="4" time="0.178369">
  </testcase>
  <testcase name="test_company_by_id_6" assertions="4" time="0.188857">
  </testcase>
  <testcase name="test_company_by_id_7" assertions="4" time="0.184056">
  </testcase>
  <testcase name="test_company_by_id_8" assertions="4" time="0.184675">
  </testcase>
  <testcase name="test_company_by_id_9" assertions="4" time="0.192803">
  </testcase>
  <testcase name="test_company_by_name" assertions="4" time="0.216308">
  </testcase>
  <testcase name="test_connection" assertions="0" time="0.067669">
  </testcase>
  <system-out>
  </system-out>
  <system-err>
  </system-err>
</testsuite>
